---
title: "cahier_bio500"
author: "Duchesne_Jordan_Grégoire_saintpierre_Lessard"
date: '2022-04-05'
output: html_document
---

# Avant de commencer :
set working directory (`setwd`) à donnees_BIO500 dans bio500 du git à Florian Jordan

Télécharger les librairies  `dyplir` et  `RSQLite`

# Données brutes
1. Télécharger les données brutes des tables de noeuds, collaborations et liens pour toutes les équipes (`read.table` ou `read.csv` selon la nature des données)
2. Vérifier chaque tables et enlever les colonnes de trop
3. Renommer les colonnes au besoin (`rename`)

Fusionner les données de liens entre elles et répéter pour collaborations et cours (`bind_rows`)

# Nettoyage des données
enlever les doublons avec `!duplicated` pour les données noeuds et cours et `distinct` pour collaborations
distinct est utilisé pour collaborations pour que la paire soit considérée et non juste étudiants 1

# Tables SQL

Création des tables SQL cours, noeuds et collaborations.
Préciser pour la nature des données pour chaque colonne ainsi que la clé primaire (`PRIMARY KEY`). Pour la table collaboration, mettre les liens avec les autres tables (`FOREIGN KEY`)

### cours
tbl_cours <- "
CREATE TABLE cours (
sigle   CHAR(6) NOT NULL,
credits       INTEGER(1) ,
obligatoire     BOOLEAN(1),
laboratoire       BOOLEAN(1),
distance   BOOLEAN(1),
groupes   BOOLEAN(1),
libre   BOOLEAN(1),
PRIMARY KEY (sigle)
);"
dbSendQuery(con, tbl_cours)


### noeuds
tbl_noeuds <- "
CREATE TABLE noeuds (
  nom_prenom      VARCHAR(50),
  annee_debut      DATE(4),
  session_debut CHAR(1),
  programme       VARCHAR(20),
  coop        BOOLEAN(1),
  PRIMARY KEY (nom_prenom)
);"
dbSendQuery(con, tbl_noeuds)

### collaborations
tbl_collaborations <- "
CREATE TABLE collaborations (
  etudiant1     VARCHAR(50),
  etudiant2     VARCHAR(50),
  sigle   CHAR(6),
  date    DATE(3),
  PRIMARY KEY (etudiant1, etudiant2, sigle,date),
  FOREIGN KEY (etudiant1) REFERENCES noeuds(nom_prenom),
  FOREIGN KEY (etudiant2) REFERENCES noeuds(nom_prenom),
  FOREIGN KEY (sigle) REFERENCES cours(sigle)
);"
dbSendQuery(con, tbl_collaborations)
dbListTables(con)

## Injection des données
Injecter les tables `noeuds`, `cours` et `collaborations` à l'aide de la fonction `dbWriteTable`

#Requête
